let AdminSettingMenus = {
  name: "Settings",
  accessLevel: "A",
  entities: [
    {
      name: "Users",
      singularName: "User",
      dbCollection: "users",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      accessLevel: "A",
    },
    {
      name: "Rates",
      singularName: "Rate",
      dbCollection: "rates",
      addFacility: false,
      deleteFacility: false,
      editFacility: true,
      accessLevel: "A",
    },
    {
      name: "Companies",
      singularName: "Company",
      dbCollection: "companies",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      accessLevel: "A",
    },
    {
      name: "Catalogs",
      singularName: "Catalog",
      dbCollection: "catalogs",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      accessLevel: "A",
    },
    {
      name: "ShopDetails",
      singularName: "ShopDetail",
      dbCollection: "shopDetails",
      addFacility: false,
      deleteFacility: false,
      editFacility: true,
      accessLevel: "A",
    },
    {
      name: "Dustbins",
      singularName: "Dustbin",
      dbCollection: "dustbins",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      accessLevel: "A",
    },
    {
      name: "Areas",
      singularName: "Area",
      dbCollection: "areas",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      accessLevel: "A",
    },
    {
      name: "Drivers",
      singularName: "Driver",
      dbCollection: "drivers",
      addFacility: true,
      deleteFacility: true,
      editFacility: true,
      accessLevel: "A",
    },
  ],
};
export default AdminSettingMenus;
